### ISSUE TITLE
Please add julia badge.

### ISSUE THREAD

**Issue by MisileLab** [Ileriayo/markdown-badges#122]
I study Julia lang and i want to get a badge in my profile but julia badge isn't avaliable.
Julialang Github:https://github.com/JuliaLang/julia

**Comment by Algebra-FUN** [comment]
The julia badge is here.
<img alt="Julia" src="https://img.shields.io/badge/Julia-9558B2?style=for-the-badge&logo=julia&logoColor=white"/>

```html
<img alt="Julia" src="https://img.shields.io/badge/Julia-9558B2?style=for-the-badge&logo=julia&logoColor=white"/>
```

I have opened a pull request half month ago, but it's not approved and merged yet.

**Comment by mehtaAnsh** [comment]
Hello, the badge and respective PR has been accepted and merged. I am closing the issue now. Apologies for the delay.
