### ISSUE TITLE
Looking for a Microsoft Power Automate badge

### ISSUE THREAD

**Issue by ishajain15** [Ileriayo/markdown-badges#138]
I was looking for a power automate badge, but there doesn't seem to be one. It would be great if someone could add one.

**Comment by gurjeetsinghvirdee** [comment]
I don't think there is a power automated badge , I find & didn't get anything like that , If someone know how to make badges then he/she will help

**Comment by gurjeetsinghvirdee** [comment]
> I was looking for a power automate badge, but there doesn't seem to be one. It would be great if someone could add one.

I don't think there is a power automated badge , I find & didn't get anything like that , If someone know how to make badges then he/she will help!

**Comment by mehtaAnsh** [comment]
Hey Isha, currently, there's no icon available for Power Automate on simple-icons (shields.io use that as their resource for icons). Once available, we would surely add it in a future Pull Request. Till that time, I am closing the issue. Once it is up, let us know by re-opening the issue. Keep contributing!
