### ISSUE TITLE
Arranging the badges

### ISSUE THREAD

**Issue by Prajwalnazre** [Ileriayo/markdown-badges#154]
While scrolling down, it was very hard for me to find and locate a specific badge. Can we arrange them in alphabetical order? It would definitely reduce the search time.

**Comment by JakyeRU** [comment]
That's a great idea, but meanwhile, you can CTRL+F and search for what you need.

**Comment by Prajwalnazre** [comment]
Oh, thanks for mentioning this shortcut though.

**Comment by Ileriayo** [comment]
I have contemplated how to achieve this, and my thinking is to have something like a pre-commit hook that lints the code, alerts you if it finds that the badges are not arranged alphabetically, then attempt to fix the arrangement where necessary.

I'll go ahead and create a discussion around this, and see if someone can come up with a solution.
cc @mehtaAnsh

**Comment by JakyeRU** [comment]
@mehtaAnsh @Prajwalnazre,
I have started a pull request (#173) to order all of the badges alphabetically. If you guys would like to contribute, I would really appreciate it!

You can use [The Alphabetizer](https://alphabetizer.flap.tv/) site to make your work easier.

**Comment by mehtaAnsh** [comment]
Hello everyone,

It is a pleasure to announce that all the badges have been arranged alphabetically. Major thanks to @JakyeRU for doing the work and @Prajwalnazre for suggesting the idea. Keep contributing guys!

My solution is to have a CI pipeline where before the merging, the script would check for the alphabetical ordering, similar to the pre-hook commit mentioned by @Ileriayo . I think we can open a separate discussion. 

I will close the issue now. Thanks to everyone who contributed!

**Comment by Prajwalnazre** [comment]
Cheers!
