### ISSUE TITLE
add gitea badge and dart badge

### ISSUE THREAD

**Issue by MisileLab** [Ileriayo/markdown-badges#169]
gitea : https://gitea.io/en-us/
dart : https://dart.dev/

**Comment by gurjeetsinghvirdee** [comment]
> gitea : https://gitea.io/en-us/
> dart : https://dart.dev/

added both badges

**Comment by MisileLab** [comment]
> > gitea : [gitea.io/en-us](https://gitea.io/en-us/)
> > dart : [dart.dev](https://dart.dev/)
> 
> added both badges

where is gitea badge?

**Comment by JakyeRU** [comment]
> > > gitea : [gitea.io/en-us](https://gitea.io/en-us/)
> > > dart : [dart.dev](https://dart.dev/)
> > 
> > 
> > added both badges
> 
> where is gitea badge?

#171

**Comment by mehtaAnsh** [comment]
Hello everyone, 
The mentioned badges have been added in different PRs. Keep adding new badges! 

I am closing the issue now.
