### ISSUE TITLE
GraphQL badge

### ISSUE THREAD

**Issue by cybercoder-naj** [Ileriayo/markdown-badges#177]
The GraphQL badge's logo color and background match and so the logo is hardly visible.

**Comment by LeonStoldt** [comment]
Hi,
I came across this problem aswell. I already created a pull request to fix this (changed icon color to white)
Hope this is helpful: https://github.com/Ileriayo/markdown-badges/pull/178

**Comment by cybercoder-naj** [comment]
Okay, awesome. Thanks for the pull request.
