### ISSUE TITLE
Issue in the UI design of Github page deployment

### ISSUE THREAD

**Issue by gokunik** [Ileriayo/markdown-badges#223]
I came to the repo to use some of the badges. I also checked the deployment and found some issues in the UI of the page.
The footer is not properly aligned and the list of markdown badges is not scrollable which makes it impossible to access all the list items. And also the list and footer overlap.

![image](https://user-images.githubusercontent.com/57342034/132996458-c8af1712-cb1b-4a41-98c5-39bf5790cc4d.png)

I thought about fixing the problem but did not found the source code. I came to know the page is hosted using Jekyll and I don't know how it works but I still wanted to contribute so I looked at the code using inspect and found the issue. I don't know where to apply the fix so I thought I can share it in the issues section.

Below are the two changes which can be done to fix the issue

```
nav {
    width: 230px;
    position: absolute;
    // This is set to fixed which makes the element fixed at its position hence it is not possible to scrolling.
    top: 0;
    left: 50%;
    margin-left: -580px;
    text-align: right; 
}
```

```
footer {
    width: 180px;
    position: fixed;
    right: 15%;  // changed the position to right instead of left:50%;
    bottom: 20px;
    text-align: right;
    line-height: 16px;
}
```
After the changes, it looked like this. 

![image](https://user-images.githubusercontent.com/57342034/132997088-04c6e82d-422a-4239-9b38-0d623f1a8a31.png)

Fixes the issue, There could have been a better fix but looking at the code it seems a pretty decent fix, just require changing two lines of code.

BTW. Can someone guide me how to contribute in the github page deployment. I am happy to contribute.

**Comment by mehtaAnsh** [comment]
Hey @gokunik , Thanks for going through the effort of fixing the bugs on the deployed web page. 

The deployed page uses Jekyll, a static site generator. I have attached a link below for your reference. Keeping the issue open so that someone can fix it.

Link: https://programminghistorian.org/en/lessons/building-static-sites-with-jekyll-github-pages

**Comment by gokunik** [comment]
I will try to understand it. If I'll get my head around it, I'll fix it by myself.
Thank you for the reference 😊.
