### ISSUE TITLE
Badge Request - Xamarin

### ISSUE THREAD

**Issue by TrentD815** [Ileriayo/markdown-badges#225]
Hey, first off, thank you for this repo, very cool idea.

I noticed that Xamarin was not on the list and could be nice to have. I was thinking it could look something like this:

`![Xamarin](https://img.shields.io/badge/Xamarin-3199DC?style=for-the-badge&logo=xamarin&logoColor=white)`

![Xamarin](https://img.shields.io/badge/Xamarin-3199DC?style=for-the-badge&logo=xamarin&logoColor=white)

What do you guys think? If everything is good I can make a PR.

**Comment by mehtaAnsh** [comment]
Hey @TrentD815 , the badge looks great. Just create a PR according to the guidelines. Thanks!

**Comment by TrentD815** [comment]
Ok awesome! I will create a PR shortly and link it to here
