### ISSUE TITLE
Please add discord.js

### ISSUE THREAD

**Issue by AviralCoder** [Ileriayo/markdown-badges#230]
There is a discord badge but I want a discord.js badge (and maybe discord.py) as well. Hope you will add it!

**Comment by LeonStoldt** [comment]
Hi @AviralCoder,
the badges are made with shields.io which is using https://simpleicons.org/ for the logo.
This logo is referenced by the name like the following:
```
![Discord](https://img.shields.io/badge/Discord-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white)
-> &logo=discord
```
![Discord](https://img.shields.io/badge/Discord-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white)

If I am correct, simpleIcons does not contain the Discord.js (or discord.py) logo.

What you could do is:

1. Submitting a request to add the Discord.js logo to simpleIcons (https://github.com/simple-icons/simple-icons/issues/new?labels=new+icon&template=icon_request.yml&title=Request%3A+)
2. Use the Discord Badge with another name: e.g. ![Discord](https://img.shields.io/badge/Discord.js-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white)
```
![Discord.js](https://img.shields.io/badge/Discord.js-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white)
```
3. Use the Discord Badge with javascript logo: e.g. ![Discord](https://img.shields.io/badge/Discord.js-%237289DA.svg?style=for-the-badge&logo=JavaScript&logoColor=white)
```
![Discord.js](https://img.shields.io/badge/Discord.js-%237289DA.svg?style=for-the-badge&logo=JavaScript&logoColor=white)
```

**Comment by AviralCoder** [comment]
Ok thanks!
