### ISSUE TITLE
Add Zustand Badge - A react state management library

### ISSUE THREAD

**Issue by naptestdev** [Ileriayo/markdown-badges#233]

**Comment by LeonStoldt** [comment]
Hi @naptestdev ,
the badges are made with shields.io which is using https://simpleicons.org/ for the logo.
This logo is referenced by the name like the following:
```
![React](https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)
-> &logo=react
```
![React](https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)

If I am correct, simpleIcons does not contain the Zustand logo.

What you could do is:

1. Submitting a request to add the Zustand logo to simpleIcons (https://github.com/simple-icons/simple-icons/issues/new?labels=new+icon&template=icon_request.yml&title=Request%3A+)
2. Use the React Badge with another name: e.g. 
![React](https://img.shields.io/badge/zustand-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)
```
![React](https://img.shields.io/badge/zustand-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)
```
OR ![React](https://img.shields.io/badge/react%20zustand-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)
```
![React](https://img.shields.io/badge/react%20zustand-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)
```

**Comment by mehtaAnsh** [comment]
The solution looks elegant, @LeonStoldt. Once the icon has been added, we would love to merge it on our repository. For now, I am closing the issue. You can reopen it once the icon gets added.
