### ISSUE TITLE
Badge Request: Vuex

### ISSUE THREAD

**Issue by rehan-sattar** [Ileriayo/markdown-badges#238]
Vuex is the state management tool for vuejs and is widely used with vuejs. I can't see any badge for it.  Please add vuex badge. 

Vuex: https://vuex.vuejs.org/

Thanks much! 🚀

**Comment by mehtaAnsh** [comment]
I would love someone to contribute here. Keeping the issue open for contributors!

**Comment by jaiakash** [comment]
I would like to contribute.

**Comment by mehtaAnsh** [comment]
> 
> 
> I would like to contribute.

Thanks for your interest. I have mentioned the rectifications. Make those, and I'll gladly accept the PR.

**Comment by mehtaAnsh** [comment]
Currently, no logo is available for VueX. Once a logo is available, just create a PR and I will be accepting it.

Reference: https://github.com/vuejs/vue/issues/6305

I will close the issue now.

**Comment by jaiakash** [comment]
Yeah I get it. VueX doesnt have logo of its own [comment](https://github.com/vuejs/vue/issues/6305#issuecomment-326679082)
maintainer mentioned to "prefer that the Vue ecosystem stick to one logo for consistency"

Anyways, looking forward to contribute to the project in future.
