### ISSUE TITLE
Missing static site generator badges

### ISSUE THREAD

**Issue by hirenchauhan2** [Ileriayo/markdown-badges#26]
Hi,

It would be nice to have a section for static site generators separately.

Let me know your thoughts on this and then I will add the section for it.

Thanks,
Hiren

**Comment by Ileriayo** [comment]
Hello @hirenchauhan2,
I'm sorry for my late response.

It would be nice to have another section for that.
Kindly raise a PR when you're done working on it.

Thanks!
