### ISSUE TITLE
Badge Request - Crystal, Zig and Nim

### ISSUE THREAD

**Issue by RaphGL** [Ileriayo/markdown-badges#276]
Requesting badge for the [Zig](https://ziglang.org/), [Crystal](https://crystal-lang.org/) and [Nim](https://nim-lang.org/) programming languages.

**Comment by mehtaAnsh** [comment]
Can someone create a Pull Request to add these programming languages? Keeping the issue open for contributors!

**Comment by userbradley** [comment]
Opened a PR for this one: #282
