### ISSUE TITLE
Few markdown tables are not been rendered properly 

### ISSUE THREAD

**Issue by Kira272921** [Ileriayo/markdown-badges#277]
I think the issue is with the markdown parser.

I have found this, I guess this might help to fix this issue: https://github.com/pages-themes/cayman/issues/82

Here are the screenshots of the tables which are not been rendered properly 
![image](https://user-images.githubusercontent.com/90365542/142434337-da76d95a-8627-41ed-82fc-08148f99c945.png)
![image](https://user-images.githubusercontent.com/90365542/142434385-e3d32499-5b93-4055-b540-7f2f93c6214b.png)
![image](https://user-images.githubusercontent.com/90365542/142434441-23fc0ecf-4257-4827-8483-f9c5c60e496f.png)
![image](https://user-images.githubusercontent.com/90365542/142434489-91619331-4da2-45d6-b3ba-b67dc3de1161.png)

**Comment by mehtaAnsh** [comment]
Hey, the issue has been resolved. Thanks @Kira272921 for resolving! I will close the issue now.
