### ISSUE TITLE
How to put some new logo while contributing

### ISSUE THREAD

**Issue by Lakshit-Chiranjiv** [Ileriayo/markdown-badges#280]
I wanted a badge for Semantic UI so I decided to contibute it but logo=semantic_ui or logo=semanticui is not helping me with any logo, So what can I do for the unavailable logos

**Comment by Lakshit-Chiranjiv** [comment]
And I have visited the simple icons site already, I didn't find semantic ui logo there,
There was just the semantic ui react logo

**Comment by mehtaAnsh** [comment]
Hey @Lakshit-Chiranjiv , the shields.io badges rely on simple-icons, and unfortunately, as you mentioned, the logo isn't available. Once it is available, you can create a PR with the mentioned guidelines. 

Just in case if you want to add it, you can create an SVG of the semantic UI icon and then create a badge. That makes the URL very lengthy, so it is a more inelegant solution. 

I will close the issue now.

**Comment by Lakshit-Chiranjiv** [comment]
okay, Got it!!
