### ISSUE TITLE
Depondabot badge gives the 404

### ISSUE THREAD

**Issue by MassivDash** [Ileriayo/markdown-badges#283]
![Dependabot](https://img.shields.io/badge/dependabot-#025E8C?style=for-the-badge&logo=dependabot&logoColor=white)

**Comment by mehtaAnsh** [comment]
Hi @MassivDash , I cannot seem to reproduce the error. Also, the question is a little ambiguous. Kindly clarify.

**Comment by MassivDash** [comment]
The badge link for Dependabot under https://img.shields.io/badge/dependabot-#025E8C?style=for-the-badge&logo=dependabot&logoColor=white gives 404: badge not found. In a previous comment I referenced the badge as described in the docs, but for me its not displayed. Accessing other badges work as expected in the MD and browser, when I hit the mentioned link above in the browser it also gives 404.

**Comment by mehtaAnsh** [comment]
Got it, thanks for the catch! Fixed it now. Keep contributing :)
