### ISSUE TITLE
Azure Badge

### ISSUE THREAD

**Issue by weeyin83** [Ileriayo/markdown-badges#296]
Your Azure badge is using the Azure DevOps logo, not the Azure logo.

**Comment by gurjeetsinghvirdee** [comment]
> Your Azure badge is using the Azure DevOps logo, not the Azure logo.

I fixed it.

**Comment by Ileriayo** [comment]
Hi @weeyin83, thanks for catching that.
Do you want to help create a PR to resolve that?

**Comment by weeyin83** [comment]
@Ileriayo I've raised a PR.

**Comment by Ileriayo** [comment]
Merged. Thanks for contributing!
