### ISSUE TITLE
Merge PR

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Ileriayo/markdown-badges#302]
Hello, 
Please check PR's and merge them it was pending from last month @Ileriayo   @mehtaAnsh

**Comment by mdoutreluingne** [comment]
I think this repository is no longer maintained and does not have much to maintain unfortunately.

I found another more popular badge repository and I think more maintained :
https://github.com/alexandresanlim/Badges4-README.md-Profile

**Comment by gurjeetsinghvirdee** [comment]
> I think this repository is no longer maintained and does not have much to maintain unfortunately.
> 
> I found another more popular badge repository and I think more maintained : https://github.com/alexandresanlim/Badges4-README.md-Profile

yeah I contribute their

**Comment by mehtaAnsh** [comment]
Hello,

I am currently not available due to personal reasons. Would resolve the pending PRs over the coming week. Apologies for the inconvenience.

**Comment by gurjeetsinghvirdee** [comment]
> Hello,
> 
> I am currently not available due to personal reasons. Would resolve the pending PRs over the coming week. Apologies for the inconvenience.

No issues!
