### ISSUE TITLE
Kallithea badge

### ISSUE THREAD

**Issue by Camroku** [Ileriayo/markdown-badges#303]
It's a Github alternative that supports Git and Mercurial
https://kallithea-scm.org/

**Comment by gurjeetsinghvirdee** [comment]
> It's a Github alternative that supports Git and Mercurial https://kallithea-scm.org/

There is no official or un official badge for this. Create
a issue in [Simple Icons](https://github.com/simple-icons/simple-icons/issues)

**Comment by mehtaAnsh** [comment]
Thanks @gurjeetsinghvirdee for pointing out. 

@Camroku Once the icons is available on simple-icons, please reopen the issue. Closing the issue now.
