### ISSUE TITLE
Blockchains related badge missing ?

### ISSUE THREAD

**Issue by realsahilsaini** [Ileriayo/markdown-badges#304]
We don't have many badges for Blockchain Developers.
For eg: Hyperledger, Truffle, etc

**Comment by gurjeetsinghvirdee** [comment]
> We don't have many badges for Blockchain Developers. For eg: Hyperledger, Truffle, etc

Hyperledger added #305 commit fa76878, right now Truffle badge doesn't exist, suggest more blockchain-related software or framework will add in next commit
