### ISSUE TITLE
Deno badge was deleted

### ISSUE THREAD

**Issue by jiyuPk** [Ileriayo/markdown-badges#307]
deno badge was deleted at commit fc0d1adc11d4b394ec0ec2e918cc3d9249783b2f

**Comment by gurjeetsinghvirdee** [comment]
> deno badge was deleted at commit [fc0d1ad](https://github.com/Ileriayo/markdown-badges/commit/fc0d1adc11d4b394ec0ec2e918cc3d9249783b2f)

In which slot ?  I will add

**Comment by jiyuPk** [comment]
https://github.com/Ileriayo/markdown-badges#frameworks-platforms-and-libraries

**Comment by gurjeetsinghvirdee** [comment]
> https://github.com/Ileriayo/markdown-badges#frameworks-platforms-and-libraries

Deno added #305 commit fa76878

**Comment by gurjeetsinghvirdee** [comment]
> https://github.com/Ileriayo/markdown-badges#frameworks-platforms-and-libraries

Badge added  #311
