### ISSUE TITLE
Add a Showwcase badge under "Social"

### ISSUE THREAD

**Issue by debaghosh** [Ileriayo/markdown-badges#329]
Hi! A 'Showwcase' badge will be great! 😊

**Comment by mehtaAnsh** [comment]
Hey @debaghosh , thanks for requesting the badge. Sadly, for a badge to be added here, it has to be available on simple-icons. (You can check the available icons at https://simple-icons.org) Once it is available, you can reopen the issue and request the badge.

Closing the issue now.
