### ISSUE TITLE
Add a Microsoft TechNet badge

### ISSUE THREAD

**Issue by tscholze** [Ileriayo/markdown-badges#330]
It would be awesome to have a Microsoft TechNet Badge - maybe under "Education"

**Comment by akashroy1** [comment]
Hi! I want to work on this. But from where should I make the badge?

**Comment by tscholze** [comment]
Hi thanks for your answer!

It seems that MSFT has no icon for TechNet anymore.
Maybe a Bold "TN" on the left side and the community name like "Surface Duo SDK" on the right?

A older logo looked like:
<img width="236" alt="Bildschirmfoto 2022-02-23 um 20 35 50" src="https://user-images.githubusercontent.com/5583469/155394681-998380d5-2439-4814-a77c-e34a2ef63e64.png">

**Comment by mehtaAnsh** [comment]
> Hi! I want to work on this. But from where should I make the badge?

Hey, you can check the icon's availability on https://simple-icons.org. If there is one, kindly follow the guidelines mentioned in the repo and create a repository.

**Comment by akashroy1** [comment]
Yea thanks for helping out I'll do it soon.

**Comment by mehtaAnsh** [comment]
Hey @akashroy1 , the subsequent PR #332 has been closed since the icon isn't available on simple-icons repo. 

Closing the issue now.
