### ISSUE TITLE
Badge Request: VsCode Insiders

### ISSUE THREAD

**Issue by CertifiedRice** [Ileriayo/markdown-badges#344]
There should be a badge for [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/)
![VSCODEINSIDERS](https://th.bing.com/th/id/OIP.9jTxJC1yLuloIl4xD1pukQHaHa?pid=ImgDet&rs=1)

**Comment by Ileriayo** [comment]
Hey @CertifiedRice,

Feel free to add a PR ;)

**Comment by CertifiedRice** [comment]
ok 😄
