### ISSUE TITLE
(Extended) Badge request

### ISSUE THREAD

**Issue by CertifiedRice** [Ileriayo/markdown-badges#346]
Every Jetbrains IDE(try starting with Rubymine and GoLand)
Jetbrains Plugins(Resharper++ and Resharper)
Visual Studio Code Insiders
Replit

**Comment by kohasummons** [comment]
- [x]  Replit

- [x] GoLand
- [ ] Visual Studio Code Insiders
- [ ] Rubymine
- [ ] Jetbrains Plugins

@CertifiedRice

**Comment by Ileriayo** [comment]
Repl badge was added in [PR 145](https://github.com/Ileriayo/markdown-badges/pull/145)

**Comment by CertifiedRice** [comment]
@kohasummons @Ileriayo  how did you make/get the JetBrains IDE icon for the SVG? 
Just curious so I can make them in the future

**Comment by kohasummons** [comment]
Aye Aye @CertifiedRice! Hope you are doing well? 😃 

Okay, I believe you are referring to the GoLand. I think It would be better if I put this into a list...

## Case 1: Logo can be found on *[Simpleicons](https://simpleicons.org/)*

1. I went over to *[Simpleicons](https://simpleicons.org/)*
2. I typed in `GoLand` into the search bar to see if the logo was actually available. Thank God GoLand was.
3. I took note of the name used by SimpleIcons for the icon, In My case `GoLand`
4. Copy any badge link from the readme or simply copy the one below
5. And Make the replacement as indicated in the dummy example

### `![🔥](https://img.shields.io/badge/🌳-⚡?style=for-the-badge&logo=🌳&logoColor=🔴)`

where:
🔥 = Name of the Icon you want to display e.g GoLand
🌳 = Name of the Icon from the Simple Icons Website e.g GoLand
⚡= Hex code for the badge background e.g #304839
🔴  = Color name for the logo e.g White

## Case 2: The logo doesn't exist on *[Simpleicons](https://simpleicons.org/)*
This one is a little bit involving. You'd have to get the Image and turn it into base64-encoded image. Copy the code and then replace 🌳 above with the code... Something like that. I've never tried it meself, though. Hope to one of these days.
![image](https://user-images.githubusercontent.com/66284362/160674265-68f4245d-29a8-42b2-a54a-943aed9de1af.png)


Did these help? 😃

**Comment by CertifiedRice** [comment]
ok ty
it helped

**Comment by kohasummons** [comment]
👋🏽 Cool

**Comment by mehtaAnsh** [comment]
> Aye Aye @CertifiedRice! Hope you are doing well? 😃
> 
> Okay, I believe you are referring to the GoLand. I think It would be better if I put this into a list...
> ## Case 1: Logo can be found on _[Simpleicons](https://simpleicons.org/)_
> 
>     1. I went over to _[Simpleicons](https://simpleicons.org/)_
> 
>     2. I typed in `GoLand` into the search bar to see if the logo was actually available. Thank God GoLand was.
> 
>     3. I took note of the name used by SimpleIcons for the icon, In My case `GoLand`
> 
>     4. Copy any badge link from the readme or simply copy the one below
> 
>     5. And Make the replacement as indicated in the dummy example
> 
> 
> ### `![🔥](https://img.shields.io/badge/🌳-⚡?style=for-the-badge&logo=🌳&logoColor=🔴)`
> 
> where: 🔥 = Name of the Icon you want to display e.g GoLand 🌳 = Name of the Icon from the Simple Icons Website e.g GoLand ⚡= Hex code for the badge background e.g #304839 🔴 = Color name for the logo e.g White
> ## Case 2: The logo doesn't exist on _[Simpleicons](https://simpleicons.org/)_
> 
> This one is a little bit involving. You'd have to get the Image and turn it into base64-encoded image. Copy the code and then replace 🌳 above with the code... Something like that. I've never tried it meself, though. Hope to one of these days. ![image](https://user-images.githubusercontent.com/66284362/160674265-68f4245d-29a8-42b2-a54a-943aed9de1af.png)
> 
> Did these help? 😃

@CertifiedRice We do have guidelines for contribution in our repo. Please do check it out, it will help you :)

**Comment by chromer030** [comment]
Please add Solaris badge too.
thank you.
