### ISSUE TITLE
F# badge

### ISSUE THREAD

**Issue by CertifiedRice** [Ileriayo/markdown-badges#357]
I would appreciate it if someone added an F# badge!

**Comment by pAkalpa** [comment]
[Simple Icons](https://simpleicons.org/) Don't have F Sharp Icon. ([Out of scope](https://github.com/simple-icons/simple-icons/issues/5043))

**Comment by CertifiedRice** [comment]
why not just make it in something like Photoshop or Adobe Illustrator?

**Comment by Texl** [comment]
F# now has an icon at Simple Icons - can we reopen this?
