### ISSUE TITLE
Add Wise Badge in the Funding

### ISSUE THREAD

**Issue by VanshSh** [Ileriayo/markdown-badges#365]
I want to add the Wise badge in the Funding section.  Though I have created the PR since I am the first-time contributor it is asking for the admin's permission to run a workflow.

Here is the PR link:

**Comment by kohasummons** [comment]
Woohoo @VanshSh!  Your PR has been merged.  Whoa, permission to run a workflow? you need none of that, mi amigo. our contribution guidelines will tell you more. Thanks for adding value here 😄
