### ISSUE TITLE
img alt attribute not found in links

### ISSUE THREAD

**Issue by B3ns44d** [Ileriayo/markdown-badges#38]
the alt attribute does not exist in the badges link

The required **alt** attribute specifies an alternate text for an image if the image cannot be displayed.

The alt attribute provides alternative information for an image if a user for some reason cannot view it (because of slow connection, an error in the src attribute, or if the user uses a screen reader).

`<img src="https://img.shields.io/badge/node.js%20-%2343853D.svg?&style=for-the-badge&logo=node.js&logoColor=white"/>`

`<img src="https://img.shields.io/badge/node.js%20-%2343853D.svg?&style=for-the-badge&logo=node.js&logoColor=white" alt="NodeJS"/>`

**Comment by B3ns44d** [comment]
I have fixed the issues by adding the alt attribute to all the badge in the readme file

**Comment by Ileriayo** [comment]
Thanks for fixing this accessibility issue.
I have requested some changes on your PR, kindly resolve the merge conflicts and I'll proceed to merge.

Thanks again!
