### ISSUE TITLE
Badge For Arduino IDE

### ISSUE THREAD

**Issue by maaz-siddiqui** [Ileriayo/markdown-badges#396]
Please add Arduino IDE badge

**Comment by maaz-siddiqui** [comment]
Add this badge in IDE Section

**Comment by byungster** [comment]
![Arduino](https://img.shields.io/badge/-Arduino-00979D?style=for-the-badge&logo=Arduino&logoColor=white)

**Comment by byungster** [comment]
![image](https://user-images.githubusercontent.com/34334571/178170405-9c029a0b-d4bb-41b9-8d4d-83ef71df3388.png)

**Comment by maaz-siddiqui** [comment]
This is showing in others, please put it in IDE section.
