### ISSUE TITLE
Can badges point to URLs?

### ISSUE THREAD

**Issue by jesusalberto18** [Ileriayo/markdown-badges#447]
Hello @Ileriayo,

Those badges have a really nice design, but I was wondering if I could add a link for receiving payments on my wallet (criptocurrency and fiat) & links to my social media accounts.

Thank You!

**Comment by kohasummons** [comment]
Hi @jesusalberto18,

Thanks for your kind words. And yes, there is a way to have the badge link to your social accounts. Here is on right now that points to my twitter account. 

[![Twitter](https://img.shields.io/badge/twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white)](https://twitter.zcom/0xkoha)

Here's the code:

```
[![Twitter](https://img.shields.io/badge/twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white)](https://twitter.com/0xkoha)
```

You can tweak this for your purposes and replace the `https://twitter.com/0xkoha` with the link you want the badge to point at and voila!

**Comment by jesusalberto18** [comment]
Thank you @kohasummons for your answer about URLs, and thank you for clearing up and labeling my question topic.

**Comment by kohasummons** [comment]
Glad I could help @jesusalberto18.  Would love to see how far you take this. Would you like me to close the issue now? :)

**Comment by jesusalberto18** [comment]
Yes, you can close it @kohasummons
