### ISSUE TITLE
Syntax HTML vs Markdown

### ISSUE THREAD

**Issue by kingthorin** [Ileriayo/markdown-badges#49]
<sup>Following from: https://github.com/Ileriayo/markdown-badges/pull/45</sup>

All the tables contain HTML syntax not markdown (per the headings). While GitHub does support this it's better to be technically correct. Either this or all of the entries should be updated to use proper Markdown syntax:
```md
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
```

Ex:
```html
<img alt="Markdown" src="https://img.shields.io/badge/markdown-%23000000.svg?&style=for-the-badge&logo=markdown&logoColor=white"/>
```
would become:
```md
![](https://img.shields.io/badge/markdown-black.svg?style=for-the-badge&logo=markdown)
```

![](https://img.shields.io/badge/markdown-black.svg?style=for-the-badge&logo=markdown)

**Comment by 727021** [comment]
Would it be better to replace the HTML with markdown syntax, or to add another column and have both?

**Comment by kingthorin** [comment]
Well the repo is named "markdown-badges" :wink:

**Comment by 727021** [comment]
Yeah. Either way, I'd be willing to go through and make those changes. @Ileriayo

**Comment by cybercoder-naj** [comment]
I am working on it now.

**Comment by mehtaAnsh** [comment]
Hello everyone, 
The repo has been officially migrated to markdown badges! Kudos to @jonbarrow for completing the majority of the work. Keep contributing! I'll close the issue now.

**Comment by kingthorin** [comment]
Nice work!

**Comment by jonbarrow** [comment]
@mehtaAnsh  @kingthorin thank you!
