### ISSUE TITLE
Badge Request - Replit

### ISSUE THREAD

**Issue by program-friedwater** [Ileriayo/markdown-badges#498]
I'd love to have a badge for [replit](https://replit.com/)

**Comment by RiteshK-611** [comment]
Replit already has badge

![Replit](https://img.shields.io/badge/Replit-DD1200?style=for-the-badge&logo=Replit&logoColor=white)

**Comment by kohasummons** [comment]
Thanks @RiteshK-611, totally missed that. 😄
