### ISSUE TITLE
Clarify or Remove Badge Style Param

### ISSUE THREAD

**Issue by kingthorin** [Ileriayo/markdown-badges#51]
<sup>Following from: https://github.com/Ileriayo/markdown-badges/pull/45</sup>

Should probably clarify `style=for-the-badge` or just not specify it.

Ref: https://shields.io/#styles

**Comment by mehtaAnsh** [comment]
Hey @kingthorin, the `style=for-the-badge` looks better than the normal, without the style-badge one. This is the only reason why I can see it being added. There's no performance difference as such too.

**Comment by kingthorin** [comment]
The documentation should still be clarified that there are other styles available and that "for-the-badge" isn't just placeholder text but is an actual style name.

**Comment by mehtaAnsh** [comment]
That actually makes sense. I'll add it in the future versions. Thanks for the insight!

**Comment by mehtaAnsh** [comment]
@kingthorin the issue has been addressed. I'll close the file now. Thanks again!
