### ISSUE TITLE
Remove Unncessary URLencoded spaces

### ISSUE THREAD

**Issue by kingthorin** [Ileriayo/markdown-badges#52]
A large number of the entries include `%20` which is a URLencoded space character, while this doesn't seem to be impacting the shields.io parsing/usage it should be removed for clarity/simplicity.

**Comment by kingthorin** [comment]
There currently seems to be 152 occurrences.

**Comment by Ileriayo** [comment]
Anybody wanna give this a fix?
Find and replace in your text editor should do it.
