### ISSUE TITLE
Add a Visual Basic icon

### ISSUE THREAD

**Issue by fffelix-jan** [Ileriayo/markdown-badges#54]
I program in Visual Basic .NET. I have to use the C# icon, because C# is the closest thing to VB.NET. (I do also know some C#, but I seem to prefer VB.NET.) May you please add a VB icon? Thanks!

**Comment by 727021** [comment]
The badges use icons from https://simpleicons.org/, which doesn't have an icon for VB. According to their website, you can request an icon be added [here](https://github.com/simple-icons/simple-icons/issues/new?template=icon_request.md).

For now, there is a badge for .NET if that helps:
<img alt=".Net" src="https://img.shields.io/badge/.NET-5C2D91?style=for-the-badge&logo=.net&logoColor=white"/>
`<img alt=".Net" src="https://img.shields.io/badge/.NET-5C2D91?style=for-the-badge&logo=.net&logoColor=white"/>`

**Comment by mehtaAnsh** [comment]
Hey @fffelix-jan , as of now, there's no icon for VB.NET available at simple-icons. You can add it in your profile readme as https://img.shields.io/badge/VB.NET-5C2D91?style=for-the-badge . Once the icon has been added, you can reopen this issue. Will close this issue for now.
