### ISSUE TITLE
How do I add my channel with youtube badge?

### ISSUE THREAD

**Issue by 1Codealot** [Ileriayo/markdown-badges#547]
Is there anyway for this badge: ![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white) to beable to add a link to my youtube channel?
`![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white)`

**Comment by kohasummons** [comment]
Hi @1Codealot, absolutely! You can wrap the badge in a Markdown template for links and it would act like a button. Let me show you how:

**Normal Youtube Badge**
Badge | URL
--- | ---
![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white) | `![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white)`

**Youtube Badge with Link SuperPower**

> click the badge,@1Codealot

Badge | URL
--- | ---
[![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white)](https://youtube.com/@kohawithstuff) | `[![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white)](https://youtube.com/@kohawithstuff)`

The format is:
[`Normal Badge URL`](Link to navigate to)

Where Normal Badge URL = `![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white)`

P.s. the badge takes you to my youtube url which is collecting dust at the moment. 🎊

**Comment by kohasummons** [comment]
You can also look at this response, https://github.com/Ileriayo/markdown-badges/issues/447#issuecomment-1272404452

**Comment by 1Codealot** [comment]
Thanks for helping!!
