### ISSUE TITLE
Badge Request - OCaml

### ISSUE THREAD

**Issue by Casper-Guo** [Ileriayo/markdown-badges#556]
OCaml is a well-known functional programming language.

[Reference logos / icons](https://github.com/ocaml/ocaml-logo)

**Comment by Athena-2003** [comment]
I have added a Pull request and added ocaml language. Reference: [e1f3065](https://github.com/Ileriayo/markdown-badges/pull/619/commits/e1f30654127d96a0e0b42046a5f4589451cfce53) and the PR number: #619

**Comment by Athena-2003** [comment]
And I don't know if this repo is participating in hacktoberfest. If it is then please add the hacktoberfest-accepted tag. I would really apprecaite it.

**Comment by Casper-Guo** [comment]
Done in #619
