### ISSUE TITLE
Add Batchfile Icon

### ISSUE THREAD

**Issue by JavaCode7** [Ileriayo/markdown-badges#57]
I have used batchfile in the past and don't see an icon for it. I would like to add it to my profile readme.

Thankyou in advance.

**Comment by 727021** [comment]
From https://github.com/Ileriayo/markdown-badges/issues/54#issuecomment-823564940:
> The badges use icons from https://simpleicons.org/, which doesn't have an icon for [batchfile]. According to their website, you can request an icon be added [here](https://github.com/simple-icons/simple-icons/issues/new?template=icon_request.md).

We could also add a badge without an icon if there isn't one.

**Comment by JavaCode7** [comment]
Thankyou @727021

**Comment by mehtaAnsh** [comment]
Hey @JavaCode7 , as of now, there's no icon for Batchfile. You can add it in your profile readme as https://img.shields.io/badge/Batchfile-5C2D91?style=for-the-badge . Once the icon has been added, you can reopen this issue. Will close this issue for now.
