### ISSUE TITLE
Stackexchange logo transparent on the badge

### ISSUE THREAD

**Issue by NoxGamingQC** [Ileriayo/markdown-badges#588]
The label color for the stackexchange badge is white and the color of the logo is set to white. That make the logo transparent. Removing the color tag fixes the issue. Pull request #589 created.

Current
![Stack Exchange](https://img.shields.io/badge/StackExchange-%23ffffff.svg?style=for-the-badge&logo=StackExchange&logoColor=white)

Proposed
![Stack Exchange](https://img.shields.io/badge/StackExchange-%23ffffff.svg?style=for-the-badge&logo=StackExchange)

**Comment by kohasummons** [comment]
Yo @NoxGamingQC. Thanks for catching that. I went ahead to review and merge your PR.

**Comment by NoxGamingQC** [comment]
Your welcome ;)
