### ISSUE TITLE
Why Markdown when they are HTML (i think)

### ISSUE THREAD

**Issue by Danix421** [Ileriayo/markdown-badges#67]
Hi, i'm Danix, a developer. I viewed this repo by the GitHub recomendations but when i opened it, viewed an error: his name is "markdown-badges" and say that there are markdown badge but they aren't markdown, they are html (i think)! This is not an urgency but i think it is bad. I hope this repo creator fix it.

**Comment by 727021** [comment]
Duplicate of #49
