### ISSUE TITLE
Badge Request: UmiJS

### ISSUE THREAD

**Issue by lakarpusky** [Ileriayo/markdown-badges#680]
https://v3.umijs.org/

**Comment by ThaddeusMercy** [comment]
Hi @kohasummons, can I work on this issue?

**Comment by kohasummons** [comment]
@ThaddeusMercy 

Yes Yes. Assigning the issue to you now.

**Comment by ThaddeusMercy** [comment]
@kohasummons I found a blocker, the UmiJs icon is not available on SimpleIcons.

**Comment by kohasummons** [comment]
Oops! Thanks for catching this. I'd close this issue now.
