### ISSUE TITLE
Add Redis Badge

### ISSUE THREAD

**Issue by NisanAyash** [Ileriayo/markdown-badges#72]
I looked for Redis technology, but I didn't find it.
I think it can be beneficial.
https://redis.io/

**Comment by sameer882000** [comment]
@NisanAyash I have added it there in the Database Section.

**Comment by NisanAyash** [comment]
@sameer882000 tnx!

**Comment by mehtaAnsh** [comment]
Hey @NisanAyash, the pull request has been merged. Thanks @sameer882000 for the PR. Appreciated. I am closing the issue now.
